# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'library(covr); codecov()'
  - r: release
    name: pgk-devs-devel
    before_script: Rscript -e "remotes::install_github(paste0('tidyverse/', c('tidyr','tibble','dplyr')))"
  - r: release
    os: osx
    name: release osx
  - r: oldrel
  - r: 3.5.3
  - r: release
    name: Strict Latin-1 locale
    before_script:
      - sudo locale-gen en_US
      - export LC_ALL=en_US
