# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

#Define multiple R-versions
r:
  - oldrel
  - release
  - devel

# CodeCov
after_success:
  - Rscript -e 'library(covr); codecov()'
